let a = [10, 20, 30, 40, 50];
console.log(a.length);
console.log(a[2]);
console.log(a.indexOf(30));
console.log(a.includes(20));
console.log(a.push(60));
console.log(a.pop());
console.log(a.shift());
console.log(a.unshift(5));
console.log(a.slice(1,4));
console.log(a.splice(2,1));
console.log(a.concat([70,80]));
console.log(a.join("-"));
console.log(a.reverse());
console.log(a.sort());
console.log(a.map(x => x * 2));
console.log(a.filter(x => x > 20));
console.log(a.reduce((t, x) => t + x, 0));
console.log(a.every(x => x > 5));
console.log(a.some(x => x > 50));
console.log([1,2,3].flat());
console.log([[1,2],[3,4]].flat());
console.log(a.find(x => x > 20));
console.log(a.findIndex(x => x > 20));
console.log(a.toString());
console.log(Array.isArray(a));
